<?php $title = 'Heroes'?>
<?php $style = 'css/style.css'?>
<?php $script = 'js/scripto.js'?>

<?php $itemAll = '/heroes'?>
<?php $itemAddNew = '/heroes/new'?>
<?php $itemSearch = '/heroes/search'?>

<?php $addInfo = true ?>
<?php $info = 'Sort by clicking on table header'?>
<?php if(count($heroes) > 0):?>
    <?php $header = 'Heroes: ' . count($heroes)?>
<?php else: ?>
    <?php $header = 'No current heroes'?>
<?php endif; ?>

<?php include 'layouts/head.php'?>
<body>
    <?php include 'layouts/navbar.php'?>

    <?php include 'layouts/othersections.php'?>

    <div class="container-fluid top-spacing">
        <?php if(count($heroes) > 0):?>
            <table id="hero-table" class="table table-bordered table-hover table-striped">
                <tr>
                    <th onclick="sortTable(0)">ID</th>
                    <th onclick="sortTable(1)">PICTURE</th>
                    <th onclick="sortTable(2)">NAME</th>
                    <th onclick="sortTable(3)">ROLE</th>
                    <th onclick="sortTable(4)">DIFFICULTY</th>
                    <th onclick="sortTable(5)">ABILITIES</th>
                    <th onclick="sortTable(6)">NATIONALITY</th>
                    <th onclick="sortTable(7)">REAL NAME</th>
                    <th>ACTIONS</th>
                </tr>
                <?php foreach($heroes as $hero): ?>
                    <tr>
                        <td><?=$hero->getId() ?></td>
                        <td class="table-hero-icon">
                            <img alt="<?=$hero->getName()?>" src="img/heroes/<?=$hero->getPictureName()?>-portrait.png">
                        </td>
                        <td><?=$hero->getName() ?></td>
                        <td><?=$hero->getRole() ?></td>
                        <td><?=$hero->getDifficulty() ?></td>
                        <td><?=$hero->getAbilities() ?></td>
                        <td><?=$hero->getNationality() ?></td>
                        <td><?=$hero->getRealName() ?></td>
                        <td>
                            <a href="<?=$router->pathFor('hero-detail', ['hero_id' => $hero->getId()])?>">
                                view
                            </a>
                            <span> | </span>
                            <a href="<?=$router->pathFor('hero-delete', ['hero_id' => $hero->getId()])?>">
                                remove
                            </a>
                            <span> | </span>
                            <a href="<?=$router->pathFor('hero-edit', ['hero_id' => $hero->getId()])?>">
                                edit
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>
    </div>

</body>
</html>