<?php $title = 'Home'?>
<?php $style = 'css/style.css'?>
<?php $script = 'js/scripto.js'?>

<?php $itemAll = '/heroes'?>
<?php $itemAddNew = '/heroes/new'?>
<?php $itemSearch = '/heroes/search'?>

<?php $addInfo = true ?>
<?php $info = 'not toxic hahaa'?>
<?php $header = 'Overwatch'?>

<?php include 'layouts/head.php'?>
<body>
    <?php include 'layouts/navbar.php'?>

    <?php include 'layouts/othersections.php'?>

</body>
</html>
